const http = require('http');
const https = require('https');
const fs = require('fs');
const path = require('path');
const swaggerUI = require('swagger-ui-express');
const jsYaml = require('js-yaml');
const express = require('express');
const cors = require('cors');
const cookieParser = require('cookie-parser');
const bodyParser = require('body-parser');
const OpenApiValidator = require('express-openapi-validator');
const logger = require('./logger');
const config = require('./config');
const workerPool = require('./workerPool');


class ExpressServer {
  constructor(port, openApiYaml) {
    this.port = port;
    this.app = express();
    this.openApiPath = openApiYaml;

    try {
      //this.schema = jsYaml.safeLoad(fs.readFileSync(openApiYaml));
      // yaml.safeLoad is removed in js-yaml 4.x, it's now just 'load'
      this.schema = jsYaml.load(fs.readFileSync(openApiYaml, 'utf8'));
    } catch (e) {
      logger.error('failed to start Express Server', e.message);
    }
    this.setupMiddleware();
  }

  setupMiddleware() {
    this.app.use(cors());
    this.app.use(bodyParser.json({ limit: '14MB' }));
    this.app.use(express.json());
    this.app.use(express.urlencoded({ extended: false }));
    this.app.use(cookieParser());
    // Leaving these here as they are useful for testing
    //Simple test to see that the server is up and responding
    //this.app.get('/hello', (req, res) => res.send(`Hello World. path: ${this.openApiPath}`));
    //Send the openapi document *AS GENERATED BY THE GENERATOR*
    //this.app.get('/openapi', (req, res) => res.sendFile((path.join(__dirname, 'api', 'openapi.yaml'))));
    //View the openapi document in a visual interface. Should be able to test from this page
    //this.app.use('/api-docs', swaggerUI.serve, swaggerUI.setup(this.schema));
 
    this.app.use(
      OpenApiValidator.middleware({
        apiSpec: this.openApiPath,
        operationHandlers: path.join(__dirname),
        validateResponses: false,
        validateApiSpec: true,
        validateRequests: true, 
        validateSecurity: true,
        validateFormats: true,
        fileUploader: { dest: config.FILE_UPLOAD_PATH },
      }),
    );

    this.app.get('/login-redirect', (req, res) => {
      res.status(200);
      res.json(req.query);
    });
    this.app.get('/oauth2-redirect.html', (req, res) => {
      res.status(200);
      res.json(req.query);
    });

    // Setup error handler
    this.app.use((err, req, res, next) => {
      //
      // IMPORTANT...this is where the runtime errors often show up
      // 
      console.error(err); // dump error to console for debug
      res.status(err.status || 500).json({
        message: err.message,
        errors: err.errors,
      });
    });
  }

  //async launch() {
  //  http.createServer(this.app).listen(this.port);
  //  logger.info(`Listening on port ${this.port}`);
  //}
  async launch() {
    if (config.HTTPS_CERT_PATH && config.HTTPS_KEY_PATH) {
      const httpsOptions = {
        key: fs.readFileSync(config.HTTPS_KEY_PATH),
        cert: fs.readFileSync(config.HTTPS_CERT_PATH),
      };

      this.server = https.createServer(httpsOptions, this.app).listen(this.port, () => {
        logger.info(`HTTPS server listening on port ${this.port}`);
      });
    } else {
      this.server = http.createServer(this.app).listen(this.port, () => {
        logger.info(`HTTP server listening on port ${this.port}`);
      });
    }
  }

  async close() {
    if (this.server !== undefined) {
      await this.server.close();
      logger.info(`Server on port ${this.port} shut down`);
    }
  }
}

module.exports = ExpressServer;
